from src.endpoints.inventory.POST.create_new_inventory import create_inventory
from src.endpoints.inventory.PUT.update_inventory_by_product_id import update_inventory_by_product_id
from src.endpoints.inventory.router_init import router
